### ISSUE TITLE
Overall document structure

### ISSUE THREAD

**Issue by gmegan** [gmegan/specification#11]
Where should the various teams API calls be placed in the overall document?

**Comment by gmegan** [comment]
It seems like the subsection with team split/destroy/my_pe/n_pes/get_options/translate should be located after memory management but before context creation. This is assuming we want to have shmem_ctx_get/set_team in the context section, so the description of teams comes before those API calls are described.

**Comment by gmegan** [comment]
The teams collectives are most similar to the active set based collectives. So the teams collectives could go in between the "all" collective call and the set collective call, e.g.
1 shmem_barrier_all
2 shmem_team_barrier
3 shmem_barrier

**Comment by nspark** [comment]
Suggest (from #20):
- Rename section title from "Teams or PE Subsets" to "Team Management Routines" for general consistency
- Move "Team Management Routines" section to precede "Communication Management Routines" section

**Comment by gmegan** [comment]
(from #20)

As per Naveens comment regarding the repeated text in the notes section of many API calls, the repeated information about default teams, and potentially other oft repeated text, should be moved up to the top of the Team Management Routines section and referenced where appropriate.

**Comment by gmegan** [comment]
Closing this issue. We can open a new issue if there are other requests for structure changes.
