### ISSUE TITLE
Add example code: shmem_team_split_2d

### ISSUE THREAD

**Issue by gmegan** [gmegan/specification#17]
Naveen has some WIP example code in this older doc:
https://docs.google.com/document/d/1rZTkcq8T8pVpejbGS7y4VgxeFwCPLKZa55U-FsrXNLk/edit

**Comment by naveen-rn** [comment]
I haven't looked at the examples completely - but https://github.com/openshmem-org/shmemx-cray-tests has more shmem_teams related tests - It iis used for Cray SHMEM testing

**Comment by gmegan** [comment]
This issue is dependent on first changing split 3d as in #23

**Comment by gmegan** [comment]
Code here needs work: https://gitlab.com/gmegan/openshmem-examples/blob/master/shmem_team/shmem_team_split_2D.c

**Comment by gmegan** [comment]
Closing this issue to be replaced with single issue for examples
