### ISSUE TITLE
Add descriptions of library constants

### ISSUE THREAD

**Issue by gmegan** [gmegan/specification#2]

**Comment by gmegan** [comment]
SHMEM_TEAM_WORLD and SHMEM_TEAM_NODE seem to belong in the library handles section, since we do not want to force them to be compile time constants.

SHMEM_TEAM_NOCOLLECTIVE seems to belong in the constants section, like the other option flags.

SHMEM_TEAM_NULL could go in either section. Adding it to constants for now, since it does not seem that we are wanting to assign this team any attributes. And since it will be used mostly to test against, likely better for performance if it is compile time.

**Comment by nspark** [comment]
> SHMEM_TEAM_NULL could go in either section. Adding it to constants for now, since it does not seem that we are wanting to assign this team any attributes. And since it will be used mostly to test against, likely better for performance if it is compile time.

I think we want `SHMEM_TEAM_NULL` to be a compile-time constant. I think similar reasoning as raised in openshmem-org/specification/issues/221 can apply here.

**Comment by naveen-rn** [comment]
Defining SHMEM_TEAM_NODE is bit tricky - we haven't defined a "NODE" in OpenSHMEM.

**Comment by gmegan** [comment]
Ah, just noticed this comment. This should probably be added as part of the general description required in Issue #15.

**Comment by gmegan** [comment]
The definition of node should probably go in the general description for Issue #15. Though you are right, it is missing from the overall OpenSHMEM programming model description, so should probably have some mention there as well.
