### ISSUE TITLE
Teams section placement and naming

### ISSUE THREAD

**Issue by nspark** [gmegan/specification#20]
Suggest:
- Rename section title from "Teams or PE Subsets" to "Team Management Routines" for general consistency
- Move "Team Management Routines" section to precede "Communication Management Routines" section

**Comment by gmegan** [comment]
As per Naveens comment regarding the repeated text in the notes section of many API calls, the repeated information about default teams, and potentially other oft repeated text, should be moved up to the top of the Team Management Routines section and referenced where appropriate.

**Comment by nspark** [comment]
This seems like a duplicate of #11. Closing and adding my comment there.
