### ISSUE TITLE
Change shmem_team_split_3D parameters and PE assignment rules

### ISSUE THREAD

**Issue by gmegan** [gmegan/specification#23]
Based on the conversation that arose during reformatting of the shmem_team_split_3d, there are some changes that are requested to be made for parameters and the assignments of PEs to teams.

The current request is to:
- Remove zrange from 3D split, so only xrange and yrange are defined and zrange is derived such that all PEs end up in a team
- Similarly remove all but xrange from 2D split, so that yrange is derived such that all PEs end up in a team

The argument is that since all PEs in the parent team must participate in the split, it is non-intuitive to have some of them not end up in some team. By contrast, in team_split_strided, only the PEs which end up in the new team must participate, and other PEs in the parent team are not required to participate in the split.

As an alternative, it is suggested that we could replace the 3D split altogether with only a 2D split with a single parameter.

So, instead of a 3D split of a 64 PE team into 4x4x4, that looks like this:
shmem_team_split_3d(team64, 0L, 4, 4, teamx, teamy, teamz)

One would get the same teams from splitting like this:
shmem_team_split_2d(team64, 0L, 16, teamx, teamz)
shmem_team_split_2d(teamx, 0L, 4, teamx, teamy)

**Comment by shamisp** [comment]
+1 on 2d with single parameter.

**Comment by gmegan** [comment]
Resolved with PR merge
