### ISSUE TITLE
Deprecate existing collectives

### ISSUE THREAD

**Issue by naveen-rn** [gmegan/specification#40]
Since, we are introducing new collectives based on teams - can we deprecate the existing ones. If not in the same ticket - a separate one?

**Comment by gmegan** [comment]
This seems reasonable to me. The old collective functionality should all be covered under teams extensions. As for separate ticket, I am not sure there is a reason unless we think there is some resistance to deprecating the old calls for some time after teams is introduced. I would think it is better to give warning messages about old collectives as soon as there is an alternative if the overall goal is to have them go away altogether.

**Comment by nspark** [comment]
Deprecating `shmem_alltoall` is handled in #43

**Comment by gmegan** [comment]
Deprecate OP_to_all is handled in #48

**Comment by gmegan** [comment]
Deprecate broadcast is handled in #49

**Comment by gmegan** [comment]
Deprecate sync is in #50
