### ISSUE TITLE
Deprecate alltoall?

### ISSUE THREAD

**Issue by gmegan** [gmegan/specification#61]
Currently the draft is deprecating sync_all and just leaving sync(SHMEM_TEAM_WORLD).

In this same spirit, would it make more sense to deprecate alltoall(dest, src, ...) and just leave alltoalls(dest, src, 1, 1, ...)?

**Comment by naveen-rn** [comment]
Implementation-wise it doesn't seem too much work. But, why is this irregularity? We have separate contiguous and strided RMAs - so why is do we just want to modify collectives.

**Comment by nspark** [comment]
Personally, I wouldn't. I think that `shmem_alltoalls` was a generalization that someone wanted, but I don't know the use-case. Since I personally care more about `shmem_alltoall`, I'd rather keep that interface.

**Comment by gmegan** [comment]
Sounds good. I will leave both in the draft. I was just in the process of rewriting alltoall/alltoalls and realized that they both have the same description with one difference of adding stride parameters. It seems good to shorten the description of alltoalls to say that it does exactly what alltoall does except with a stride value, or vice versa. Since it sounds like alltoall is the more common usage, I can leave it as the default with the full description and shorten alltoalls.

**Comment by gmegan** [comment]
Leaving alltoall and alltoalls in the draft. Closing this issue.
